<?php
$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller' => 'registration', 'action' => 'forgotten-password-change')));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>


    <h1 class="page-title-wrapper text-center margin-bottom-30 label-info padding-v-10 label-styled"> Ustal nowe hasło</h1>
    <div class="row">
        <div class="pagepadding">
            <div class="col-xs-12 col-sm-6 col-lg-6 col-sm-offset-3 col-lg-offset-3">
                <div class="form-group" id="username-div">
                    <div>
                        <?php echo $this->formRow($form->get('usr_password_new')); ?>
                        <?php echo $this->formRow($form->get('usr_password_new_confirm')); ?>
                        <?php echo $this->formRow($form->get('usr_token')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formSubmit($form->get('submit'));
                    echo $this->form()->closeTag();?>
                </div>
            </div>
        </div>
    </div>