<?php
$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller' => 'registration', 'action' => 'forgotten-password')));
$form->prepare();
?>

<h1 class="page-title-wrapper text-center margin-bottom-30 label-info padding-v-10 label-styled"> Przypominanie hasła</h1>
<div class="row">
    <div class="pagepadding">
    <div class="col-xs-12 col-sm-6 col-lg-6 col-sm-offset-3 col-lg-offset-3">
        <article class="text-justify bg-info form-group"> Wpisz adres e-mail użytkownika na który ma zostać wysłana wiadomość zawierająca link do ponownego wygenerowania hasła.</article>
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group" id="username-div">
                <label for="usr_name" class="login-label">Adres e-mail użytkownika</label></br>
                <div>
                    <div id="icon-input">
                    </div>
                    <?php echo $this->formRow($form->get('usr_email')); ?>
                </div>
            </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit'));
               echo $this->form()->closeTag();?>
        </div>
    </div>
    </div>
</div>
<?
?>