<div class="">
<div class="">
    <div class="email-header">
        <span class="title">Atrakcje Krakowa</span>
    </div>
    <div class="email-content">
        <span class="title1">Prawie ukończono!</span></br>

        <span class="title2">Jeśli nie rejestrowałeś się na portalu Atrakcje Krakowa zignoruj tę wiadomość.</span>
    </div>
    <div class="registration-button-area">
        <a href=""><div class="registration-button">Kliknij tutaj aby dokończyć rejestrację!</div></a>
    </div>
    </div>
</div>
<style>

.registration-button-area
{
    padding: 10px 10px 20px 10px;
    width: 300px;
}

.email-header
{
    border: 2px solid #1F80B0;
    text-align: center;
    padding: 20px;
    font-size: 33px;
    color: #2aabd2;
    background-color: #2a5d84;
    text-decoration: underline;
    text-decoration-color: #2aabd2;
}
.title
    {
        border-bottom: 5px solid #eb9316;
    }
.email-content
{
    border: 2px solid #1F80B0;
    padding: 20px 20px;
    margin: 20px 10px;
}

.title1
{
    font-size: 15px;
    font-weight: 700;
}
.registration-button
{
    padding: 20px 10px;
    background-color: #2a5d84;
    border-radius: 10px;
    color: #fff;
}
    a
    {
    color: #fff;
    text-decoration: none;
    }

.registration-button:hover
    {
        background-color: #2a6496;
    }
</style>