<div class="">
    <div class="">
        <div class="email-content">
            <span class="title1">Uwaga!</span></br>
            <span class="title2">Podany link do zmiany hasła jest nieaktywny</span>
        </div>
    </div>
</div>
<style>
    .email-content
    {
        border: 2px solid #1F80B0;
        padding: 20px 20px;
        margin: 20px 10px;
    }

    .title1
    {
        font-size: 15px;
        font-weight: 700;
    }
    a
    {
        color: #fff;
        text-decoration: none;
    }

</style>